[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/submodules/multimedia-toolbox/*"
  to = "/submodules/multimedia-toolbox/"
  status = 200

[[redirects]]
  from = "/submodules/*"
  to = "/submodules/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200